modules/bo/models/User.php
<?php

namespace app\modules\bo\models;
use yii\base\NotSupportedException;
use yii\db\ActiveRecord;
use yii\helpers\Security;
use yii\web\IdentityInterface;
use yii\behaviors\TimestampBehavior;

class User extends \yii\db\ActiveRecord  implements IdentityInterface
{
    public $auth_key;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'admins';
    }
 
    public static function findIdentity($id){
        return static::findOne($id);
    }

    public static function findIdentityByAccessToken($token, $type = null){
        throw new NotSupportedException('Not have access token field');
    }

    public function getId(){
        return $this->id;
    }

    public function getName(){
        return $this->name;
    }

    public function getAuthKey(){
        return $this->auth_key;
    }

    public function validateAuthKey($authKey){
        return $this->getAuthKey() === $authKey;
    }

    public static function findByUsername($username){
        return self::findOne(['username'=>$username]);
    }

    public static function findByEmail($email){
        return self::find()
                        ->with('role.menus.childrens')
                        ->where(['admins.email'=>$email])
                        ->one();
    }

    public function validatePassword($password){
        return Yii::$app->getSecurity()->validatePassword($password, $this->password);
    }

    public function getRole(){
        return $this->hasOne(Roles::className(), ['id' => 'role_id']);
    }

    public static function find()
    {
        return parent::find()->onCondition(['admins.is_deleted' => '0']);
    }
}

modules/bo/controllers/DefaultController.php
<?php

namespace app\modules\bo\controllers;

use Yii;
use yii\web\Controller;
use app\modules\bo\models\User;

/**
 * Default controller for the `bopanel` module
 */
class DefaultController extends Controller
{
    public $layout = '@app/views/layouts/controlpanel.php';
    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        $app = Yii::$app->userbo->identity;
        return $this->render('index');
    }
}

modules/bo/controllers/UsersController.php
<?php

namespace app\modules\bo\controllers;

use Yii;
use yii\helpers\Url;
use app\helpers\MyLibs;
use app\controllers\BaseController as Controller;
use app\modules\bo\models\User;
use app\modules\bo\models\Roles;
use thamtech\uuid\helpers\UuidHelper;
use app\helpers\Logs;

/**
 * Default controller for the `bopanel` module
 */
class UsersController extends Controller
{
    public $layout = '@app/views/layouts/controlpanel.php';
    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('@app/modules/bo/views/manajemen/users/index');
    }

    public function actionDrawTable(){
        $request = Yii::$app->request->get();

        $draw = $request['draw'];
        $start = $request['start'];
        $rowperpage = $request['length']; // Rows display per page
        $searchKey = $request['q'] ?? '';

        $columnIndex_arr = $request['order'];
        $columnName_arr = $request['columns'];
        $order_arr = $request['order'];
        $search_arr = $request['search'];

        $columnIndex = $columnIndex_arr[0]['column']; // Column index
        $columnName = $columnName_arr[$columnIndex]['data']; // Column name
        $columnSortOrder = $order_arr[0]['dir'] === 'asc' ? SORT_ASC : SORT_DESC; // asc or desc
        $searchValue = $search_arr['value']; // Search value

        // Total records
        $totalRecords = User::find()
                                ->where([])
                                ->count();
        $totalRecordswithFilter = User::find()
                                ->joinWith(['role'])
                                ->where(['like', 'admins.email', '%' . $searchValue . '%', false])
                                ->orWhere(['like', 'admins.name', '%' . $searchValue . '%', false])
                                ->orWhere(['like', 'roles.name', '%' . $searchValue . '%', false])
                                ->count();

        // Fetch records
        $records = User::find()
                    ->joinWith(['role'])
                    ->where(['like', 'admins.email', '%' . $searchValue . '%', false])
                    ->orWhere(['like', 'admins.name', '%' . $searchValue . '%', false])
                    ->orWhere(['like', 'roles.name', '%' . $searchValue . '%', false])
                    ->orderBy([$columnName => $columnSortOrder])
                    ->limit($rowperpage)
                    ->offset($start)
                    ->all();

        $data_arr = array();

        foreach($records as $record){
            $btn = [
                'edit' => [
                    'to' => Url::toRoute(['users/edit','id' => $record->id]),
                    'class' => 'btn btn-sm btn-warning',
                    'icon' => 'icofont icofont-ui-edit'
                ],
                'delete' => [
                    'to' => 'javascript:void(0)',
                    'class' => 'btn btn-sm btn-danger',
                    'icon' => 'icofont icofont-trash',
                    'onclick' => 'tableDelete(\''.$record->id.'\')',
                ]
            ];
            
            $created_at = !empty($record->created_at) ? date('d M Y',strtotime($record->created_at)) : '*';
            $updated_at = !empty($record->updated_at) ? date('d M Y',strtotime($record->updated_at)) : '*';

            $data_arr[] = array(
                'name' => $record->name ?? '*',
                'email' => $record->email ?? '*',
                'role' => $record->role->name ?? '*',
                'created_at' => $created_at,
                'updated_at' => $updated_at,
                'action' => $this->dtButton($btn)
            );
        }

        $response = array(
            'draw' => intval($draw),
            'iTotalRecords' => $totalRecords,
            'iTotalDisplayRecords' => $totalRecordswithFilter,
            'aaData' => $data_arr,
            'realData' => $records
        );

        return $this->asJsonDatatable($response,'Berhasil mendisplay data.');
    }

    public function actionCreate(){
        $model['roleOptions'] = Roles::find()
                                    ->select(['name'])
                                    ->indexBy('id')
                                    ->column();
        return $this->render('@app/modules/bo/views/manajemen/users/form',$model);
    }

    public function actionSave(){
        $request = Yii::$app->request->post();

        $transaction = Yii::$app->db->beginTransaction();
        $hash = Yii::$app->getSecurity();

        Yii::$app->timeZone = 'Asia/Jakarta';

        try {
            $passwordGenerated = MyLibs::digitRandom(6);

            $user = new User();
            $user->id = UuidHelper::uuid();
            $user->name = $request['name'] ?? '';
            $user->username = $request['email'] ?? '';
            $user->email = $request['email'] ?? '';
            $user->password = $hash->generatePasswordHash($passwordGenerated);
            $user->created_at = date('Y-m-d H:i:s');
            $user->role_id = $request['role_id'];

            if(!$user->save()){
                throw Exception('Unable to save record.');
            }

            $role = Roles::findOne(['id' => $request['role_id']]);

            $html = Yii::$app->mailer
                    ->render(
                        '@app/mail/otp', 
                        [
                            'nama_lengkap' =>  $request['name'],
                            'email' =>  $request['email'],
                            'role' =>  $role->name,
                            'password' =>  $passwordGenerated,
                        ], 
                        '@app/mail/layouts/html'
                    );

            $mailData['fromName'] = 'JOS Indonesia';
            $mailData['senderName'] = 'no-reply@jos.id';
            $mailData['to'] = $request['email'];
            $mailData['subject'] = 'Password Login Kamu.';
            $mailData['konten'] = $html;

            MyLibs::SendMail($mailData);

            $callback = ['callback' => Url::toRoute(['users/index'])];

            $transaction->commit();

            // log 
            Logs::save([
                'controller' => Yii::$app->controller->id,
                'topic' => 'CREATE RESOURCE',
                'activity' => 'berhasil membuat user',
                'status' => 'SUCCESS',
            ]);

        } catch (\Throwable $th) {
            $transaction->rollback();

            // log 
            Logs::save([
                'controller' => Yii::$app->controller->id,
                'topic' => 'CREATE RESOURCE',
                'activity' => 'user gagal membuat roles',
                'reason' => $th->getMessage(),
                'status' => 'ERROR'
            ]);

            return $this->asJsonError([$th->getMessage()],'Gagal menyimpan data.');
        }
        return $this->asJsonSuccess($callback,'Berhasil menyimpan data.');
    }

    public function actionEdit(){
        $id = Yii::$app->request->get()['id'];

        $model['roleOptions'] = Roles::find()
                                    ->select(['name'])
                                    ->indexBy('id')
                                    ->column();
        $model['id'] = $id;
        $model['user'] = User::findOne(['id' => $id]);
        return $this->render('@app/modules/bo/views/manajemen/users/form',$model);
    }

    public function actionUpdate(){
        $request = Yii::$app->request->post();

        $transaction = Yii::$app->db->beginTransaction();
        $hash = Yii::$app->getSecurity();

        Yii::$app->timeZone = 'Asia/Jakarta';

        try {
            $passwordGenerated = MyLibs::digitRandom(6);

            $user = User::findOne(['id' => $request['id']]);
            $user->name = $request['name'] ?? '';
            $user->role_id = $request['role_id'];
            $user->updated_at = date('Y-m-d H:i:s');

            if(!$user->save()){
                throw Exception('Unable to save record.');
            }

            $callback = ['callback' => Url::toRoute(['users/index'])];

            $transaction->commit();

            // log 
            Logs::save([
                'controller' => Yii::$app->controller->id,
                'topic' => 'UPDATE RESOURCE',
                'activity' => 'berhasil mengubah user',
                'status' => 'SUCCESS',
            ]);

        } catch (\Throwable $th) {
            $transaction->rollback();

            // log 
            Logs::save([
                'controller' => Yii::$app->controller->id,
                'topic' => 'UPDATE RESOURCE',
                'activity' => 'gagal mengubah roles',
                'reason' => $th->getMessage(),
                'status' => 'ERROR'
            ]);

            return $this->asJsonError([$th->getMessage()],'Gagal menyimpan data.');
        }
        return $this->asJsonSuccess($callback,'Berhasil menyimpan data.');
    }

    public function actionDelete(){
        $id = Yii::$app->request->get()['id'];
        
        $transaction = Yii::$app->db->beginTransaction();

        Yii::$app->timeZone = 'Asia/Jakarta';

        try {
            $model = User::findOne(['id' => $id]);
            $model->updated_at = date('Y-m-d H:i:s');
            $model->is_deleted = '1';
            if(!$model->save()){
                throw Exception('Unable to save record.');
            }

            $transaction->commit();

            // log 
            Logs::save([
                'controller' => Yii::$app->controller->id,
                'topic' => 'DELETE RESOURCE',
                'activity' => 'berhasil menghapus user',
                'status' => 'SUCCESS',
            ]);

        } catch (\Throwable $th) {
            $transaction->rollback();

            // log 
            Logs::save([
                'controller' => Yii::$app->controller->id,
                'topic' => 'DELETE RESOURCE',

modules/bo/views/manajemen/users/_footer.php
<?php 
    $jsfiles = [
        'js/user/index.js',
    ];

    foreach ($jsfiles as $key => $file) {
        $this->registerJsFile('@web/'.$file, ['position' => \yii\web\View::POS_END]);
    }
?>

modules/bo/views/manajemen/users/form.php
<?php 
    use yii\helpers\Url;
    use yii\widgets\ActiveForm;
    use yii\helpers\Html;
?>
<div class="page-header">
    <div class="row align-items-end">
        <div class="col-lg-8">
            <div class="page-header-title">
                <div class="d-inline">
                    <h4>Manajemen Users - Add User</h4>
                    <span>Form tambah data user business operational.</span>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="page-header-breadcrumb">
                <ul class="breadcrumb-title">
                    <li class="breadcrumb-item">
                        <a href="<?= Url::toRoute(['default/index']); ?>"><i class="feather icon-home"></i> </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="<?= Url::toRoute(['users/index']); ?>">Daftar data user</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#!">Tambah data user</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- BEGIN: FORM -->
<div class="card">
    <div class="card-block">
        <div class="row">
            <div class="col-md-8 mx-auto">
            <?php 
                $form = ActiveForm::begin([
                    'method' =>
                    'POST', 'id' => 'formUser', 
                    'options' => ['class' => 'form-horizontal'],
                ]); 
            ?>
            
            <?php 
                if(isset($id)){
            ?>
                <input id="hiddenId" type="hidden" name="id" value="<?= $id ?? ''; ?>" />
            <?php
                }
            ?>
            <div class="form-group">
                <label for="name" class="label-input">Nama Lengkap</label>
                <input type="text" 
                        class="form-control" 
                        name="name" 
                        value="<?= $user->name ?? ''; ?>" 
                        placeholder="Input nama lengkap kamu disini"
                    />
                <div class="error-wrapper"></div>
            </div>

            <div class="form-group">
                <label for="email" class="label-input">Email</label>
                <input type="text" 
                        class="form-control" 
                        name="email" 
                        value="<?= $user->email ?? ''; ?>"
                        placeholder="Input email kamu disini"
                        <?= isset($id) ? 'readonly' : ''; ?>
                    />
                <div class="error-wrapper"></div>
            </div>

            <div class="form-group">
                <label for="role">Role</label>
                <?php echo Html::dropDownList('role_id',
                                                $user->role_id ?? '', 
                                                $roleOptions, 
                                                [
                                                    'prompt' => '--- Pilih Role ---',
                                                    'class' => 'form-control roledropdown',
                                                ]); 
                                            ?>
                <div class="error-wrapper"></div>
            </div>

            <div class="form-group" style="text-align:center">
                <a 
                    href="<?= Url::toRoute(['users/index']); ?>"
                    class="float-right btn btn-danger" 
                    style="font-size:18px; margin-left:10px;">
                    <i class="fa fa-remove"></i> Batal
                </a>

                <?php 
                    $action = Url::toRoute(['users/save']);
                    if(isset($id)){
                        $action = Url::toRoute(['users/update']);
                    }
                ?>
                <button 
                        id="usersSave"
                        type="button" 
                        class="float-right btn btn-primary" 
                        style="font-size:18px;"
                        onclick="save('<?= $action; ?>')">
                    <i class="fa fa-save"></i> Simpan
                </button>
            </div>

            <?php ActiveForm::end() ?>
            </div>
        </div>
    </div>
</div>
<!-- END: FORM -->

<?= $this->context->renderPartial('@app/modules/bo/views/manajemen/users/_footer'); ?>

modules/bo/views/manajemen/users/index.php
<?php use yii\helpers\Url; ?>
<div class="page-header">
    <div class="row align-items-end">
        <div class="col-lg-8">
            <div class="page-header-title">
                <div class="d-inline">
                    <h4>Manajemen Users - Daftar User</h4>
                    <span>Daftar data user business operational.</span>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="page-header-breadcrumb">
                <ul class="breadcrumb-title">
                    <li class="breadcrumb-item">
                        <a href="<?= Url::toRoute(['default/index']); ?>"><i class="feather icon-home"></i> </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#!">Daftar data user</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="card">
    <!-- CARD HEADER -->
    <div class="card-block">
        <div>
            <a href="<?= Url::toRoute(['users/create']); ?>" class="btn btn-mat btn-primary"><i class="icofont icofont-users"></i> Tambah User</a>
        </div>
        <div class="spacer"></div>
        <div class="dt-responsive table-responsive">
            <table id="dtUsers" class="table table-striped table-bordered nowrap mytable" load-url="<?= Url::toRoute(['users/draw-table']); ?>">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Role</th>
                        <th>Created at</th>
                        <th>Updated at</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Role</th>
                        <th>Created at</th>
                        <th>Updated at</th>
                        <th>Action</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>

<?= $this->context->renderPartial('@app/modules/bo/views/manajemen/users/_footer'); ?>