modules/bo/models/Menu.php
<?php

namespace app\modules\bo\models;

class Menu extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'menus';
    }

    public function getChildrens()
    {
        return $this->hasMany(self::className(), ['parent' => 'id'])
                    ->orderBy([
                        'menus.sort_number' => SORT_ASC
                    ]);
    }

    public function getRoles(){
        return $this->hasMany(Roles::className(), ['id' => 'role_id'])
                    ->viaTable('roles_access', ['role_id' => 'id']);
    }

    public static function find()
    {
        return parent::find()->onCondition(['menus.is_deleted' => '0']);
    }
}

modules/bo/controllers/DefaultController.php
<?php

namespace app\modules\bo\controllers;

use Yii;
use yii\web\Controller;
use app\modules\bo\models\User;

/**
 * Default controller for the `bopanel` module
 */
class DefaultController extends Controller
{
    public $layout = '@app/views/layouts/controlpanel.php';
    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        $app = Yii::$app->userbo->identity;
        return $this->render('index');
    }
}

modules/bo/controllers/MenusController.php
<?php

namespace app\modules\bo\controllers;

use Yii;
use yii\helpers\Url;
use app\controllers\BaseController as Controller;
use app\modules\bo\models\Menu;
use app\modules\bo\models\Icons;
use app\helpers\Logs;


/**
 * Default controller for the `bopanel` module
 */
class MenusController extends Controller
{
    public $layout = '@app/views/layouts/controlpanel.php';
    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('@app/modules/bo/views/manajemen/menus/index');
    }

    public function actionDrawTable(){
        $request = Yii::$app->request->get();

        $menus = Menu::find()->all();

        $data_arr = array();

        foreach ($menus as $key => $record) {
            $btn = [
                'edit' => [
                    'to' => Url::toRoute(['menus/edit','id' => $record->id]),
                    'class' => 'btn btn-sm btn-warning',
                    'icon' => 'icofont icofont-ui-edit'
                ],
                'delete' => [
                    'to' => 'javascript:void(0)',
                    'class' => 'btn btn-sm btn-danger',
                    'icon' => 'icofont icofont-trash',
                    'onclick' => 'tableDelete(\''.$record->id.'\')',
                ]
            ];
                        
            $data_arr[] = array(
                'tt_key' => intVal($record->id),
                'tt_parent' => ($record->parent === '*') ? intVal(0) : intVal($record->parent),
                'name' => $record->name,
                'path' => $record->path,
                'icon' => $record->icon,
                'created_at' => $record->created_at,
                'updated_at' => $record->updated_at,
                'action' => $this->dtButton($btn)
            );
        }

        return $this->asJson($data_arr,'[Success] display data...');
    }

    public function actionCreate(){
        $model['menuOptions'] = Menu::find()
                                    ->select(['name'])
                                    ->indexBy('id')
                                    ->where(['parent' => '0'])
                                    ->column();
        $model['iconOptions'] = Icons::find()
                                    ->select(['icon'])
                                    ->indexBy('icon')
                                    ->column();

        return $this->render('@app/modules/bo/views/manajemen/menus/form',$model);
    }

    public function actionSave(){
        $request = Yii::$app->request->post();

        $transaction = Yii::$app->db->beginTransaction();
        $hash = Yii::$app->getSecurity();
        
        $max = Menu::find()->max('sort_number');

        Yii::$app->timeZone = 'Asia/Jakarta';

        try {
            $menu = new Menu();
            $menu->name = $request['name'] ?? '';
            $menu->sort_number = intVal($max) + 1;
            $menu->path = !empty($request['path']) ? $request['path'] : '#';
            $menu->icon = $request['icon'] ?? '';
            $menu->parent = (empty($request['parent']) || $request === '') ? '0' : $request['parent'];
            $menu->created_at = date('Y-m-d H:i:s');

            if(!$menu->save()){
                throw Exception('Unable to save record.');
            }

            $callback = ['callback' => Url::toRoute(['menus/index'])];

            $transaction->commit();

            // log 
            Logs::save([
                'controller' => Yii::$app->controller->id,
                'topic' => 'CREATE RESOURCE',
                'activity' => 'user berhasil membuat menu',
                'status' => 'SUCCESS',
            ]);
            
        } catch (\Throwable $th) {
            $transaction->rollback();

            // log 
            Logs::save([
                'controller' => Yii::$app->controller->id,
                'topic' => 'CREATE RESOURCE',
                'activity' => 'user gagal membuat menu',
                'reason' => $th->getMessage(),
                'status' => 'ERROR'
            ]);

            return $this->asJsonError([$th->getMessage()],'Gagal menyimpan data.');
        }
        return $this->asJsonSuccess($callback,'Berhasil menyimpan data.');
    }

    public function actionEdit(){
        $id = Yii::$app->request->get()['id'];

        $model['menuOptions'] = Menu::find()
                                    ->select(['name'])
                                    ->indexBy('id')
                                    ->where(['parent' => '0'])
                                    ->column();
        $model['iconOptions'] = Icons::find()
                                    ->select(['icon'])
                                    ->indexBy('icon')
                                    ->column();
        $model['id'] = $id;
        $model['menu'] = Menu::findOne(['id' => $id]);
        return $this->render('@app/modules/bo/views/manajemen/menus/form',$model);
    }

    public function actionUpdate(){
        $request = Yii::$app->request->post();

        $transaction = Yii::$app->db->beginTransaction();
        $hash = Yii::$app->getSecurity();
        
        $max = Menu::find()->max('sort_number');

        Yii::$app->timeZone = 'Asia/Jakarta';

        try {
            $menu = Menu::find()->where(['id' => $request['id']])->one();
            $menu->name = $request['name'] ?? '';
            $menu->path = !empty($request['path']) ? $request['path'] : '#';
            $menu->icon = $request['icon'] ?? '';
            $menu->parent = (empty($request['parent']) || $request === '') ? '0' : $request['parent'];
            $menu->created_at = date('Y-m-d H:i:s');

            if(!$menu->save()){
                throw Exception('Unable to save record.');
            }

            $callback = ['callback' => Url::toRoute(['menus/index'])];

            $transaction->commit();

            // log 
            Logs::save([
                'controller' => Yii::$app->controller->id,
                'topic' => 'UPDATE RESOURCE',
                'activity' => 'user berhasil mengubah menu',
                'status' => 'SUCCESS',
            ]);
        } catch (\Throwable $th) {
            $transaction->rollback();

            // log 
            Logs::save([
                'controller' => Yii::$app->controller->id,
                'topic' => 'UPDATE RESOURCE',
                'activity' => 'user gagal mengubah menu',
                'reason' => $th->getMessage(),
                'status' => 'ERROR'
            ]);

            return $this->asJsonError([$th->getMessage()],'Gagal menyimpan data.');
        }
        return $this->asJsonSuccess($callback,'Berhasil menyimpan data.');
    }

    public function actionDelete(){
        $id = Yii::$app->request->get()['id'];
        
        $transaction = Yii::$app->db->beginTransaction();

        Yii::$app->timeZone = 'Asia/Jakarta';

        try {
            $model = Menu::findOne(['id' => $id]);
            $model->updated_at = date('Y-m-d H:i:s');
            $model->is_deleted = '1';
            if(!$model->save()){
                throw Exception('Unable to save record.');
            }

            $callback = ['callback' => Url::toRoute(['menus/index'])];

            $transaction->commit();

            // log 
            Logs::save([
                'controller' => Yii::$app->controller->id,
                'topic' => 'DELETE RESOURCE',
                'activity' => 'user berhasil menghapus menu',
                'status' => 'SUCCESS',
            ]);

        } catch (\Throwable $th) {
            $transaction->rollback();

            // log 
            Logs::save([
                'controller' => Yii::$app->controller->id,
                'topic' => 'DELETE RESOURCE',
                'activity' => 'user gagal menghapus menu',
                'reason' => $th->getMessage(),
                'status' => 'ERROR'
            ]);

            return $this->asJsonError([$th->getMessage()],'Gagal menghapus data.');
        }

        return $this->asJsonSuccess($callback,'Berhasil menghapus data.');
    }
}

modules/bo/views/manajemen/menus/_footer.php
<?php 
    $jsfiles = [
        'js/treetable/treeTable.js',
        'js/menu/index.js',
    ];

    $cssfiles = [
        'js/treetable/tree-table.min.css',
    ];

    foreach ($jsfiles as $key => $file) {
        $this->registerJsFile('@web/'.$file, ['position' => \yii\web\View::POS_END]);
    }

    foreach ($cssfiles as $key => $file) {
        $this->registerCssFile('@web/'.$file, ['position' => \yii\web\View::POS_HEAD]);
    }
?>

modules/bo/views/manajemen/menus/form.php
<?php 
    use yii\helpers\Url;
    use yii\widgets\ActiveForm;
    use yii\helpers\Html;
?>
<div class="page-header">
    <div class="row align-items-end">
        <div class="col-lg-8">
            <div class="page-header-title">
                <div class="d-inline">
                    <h4>Manajemen Menus - Add Menu</h4>
                    <span>Form tambah data menu.</span>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="page-header-breadcrumb">
                <ul class="breadcrumb-title">
                    <li class="breadcrumb-item">
                        <a href="<?= Url::toRoute(['default/index']); ?>"><i class="feather icon-home"></i> </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="<?= Url::toRoute(['users/index']); ?>">Daftar data menu</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#!">Tambah data menu</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- BEGIN: FORM -->
<div class="card">
    <div class="card-block">
        <div class="row">
            <div class="col-md-8 mx-auto">
            <?php 
                $form = ActiveForm::begin([
                    'method' =>
                    'POST', 'id' => 'formMenu', 
                    'options' => ['class' => 'form-horizontal'],
                ]); 
            ?>
            
            <?php 
                if(isset($id)){
            ?>
                <input id="hiddenId" type="hidden" name="id" value="<?= $id ?? ''; ?>" />
            <?php
                }
            ?>
            <div class="form-group">
                <label for="name" class="label-input">Nama Menu</label>
                <input type="text" 
                        class="form-control" 
                        name="name" 
                        value="<?= $menu->name ?? ''; ?>" 
                        placeholder="Input nama menu kamu disini"
                    />
                <div class="error-wrapper"></div>
            </div>

            <div class="form-group">
                <label for="email" class="label-input">Path</label>
                <input type="text" 
                        class="form-control" 
                        name="path" 
                        value="<?= $menu->path ?? ''; ?>"
                        placeholder="Input path menu kamu disini"
                    />
                <div class="error-wrapper"></div>
            </div>

            <div class="form-group">
                <label for="email" class="label-input pickicon">
                    Icon
                    <div id="display-icon" class="list-icon">
                        <i class="feather <?= isset($menu->icon) ? $menu->icon :  'icon-alert-octagon'; ?>"></i>
                    </div>
                </label>
                <?php echo Html::dropDownList('icon',
                                                $menu->icon ?? '', 
                                                $iconOptions, 
                                                [
                                                    'prompt' => 'Pilih Icon',
                                                    'class' => 'icondropdown',
                                                ]); 
                                            ?>
                <div class="error-wrapper"></div>
            </div>

            <div class="form-group">
                <label for="role">Menu Parent</label>
                <?php echo Html::dropDownList('parent',
                                                $menu->role_id ?? '', 
                                                $menuOptions, 
                                                [
                                                    'prompt' => 'Pilih Menu',
                                                    'class' => 'form-control roledropdown',
                                                ]); 
                                            ?>
                <div class="error-wrapper"></div>
            </div>

            <div class="form-group" style="text-align:center">
                <a 
                    href="<?= Url::toRoute(['menus/index']); ?>"
                    class="float-right btn btn-danger" 
                    style="font-size:18px; margin-left:10px;">
                    <i class="fa fa-remove"></i> Batal
                </a>

                <?php 
                    $action = Url::toRoute(['menus/save']);
                    if(isset($id)){
                        $action = Url::toRoute(['menus/update']);
                    }
                ?>
                <button 
                        id="menusSave"
                        type="button" 
                        class="float-right btn btn-primary" 
                        style="font-size:18px;"
                        onclick="save('<?= $action; ?>')">
                    <i class="fa fa-save"></i> Simpan
                </button>
            </div>

            <?php ActiveForm::end() ?>
            </div>
        </div>
    </div>
</div>
<!-- END: FORM -->

<?= $this->context->renderPartial('@app/modules/bo/views/manajemen/menus/_footer'); ?>

modules/bo/views/manajemen/menus/index.php
<?php use yii\helpers\Url; ?>
<div class="page-header">
    <div class="row align-items-end">
        <div class="col-lg-8">
            <div class="page-header-title">
                <div class="d-inline">
                    <h4>Manajemen Menus - Daftar Menu</h4>
                    <span>Daftar data menu.</span>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="page-header-breadcrumb">
                <ul class="breadcrumb-title">
                    <li class="breadcrumb-item">
                        <a href="<?= Url::toRoute(['default/index']); ?>"><i class="feather icon-home"></i> </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#!">Daftar data menu</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="card">
    <!-- CARD HEADER -->
    <div class="card-block">
        <div>
            <a href="<?= Url::toRoute(['menus/create']); ?>" class="btn btn-mat btn-primary"><i class="icofont icofont-chart-flow"></i> Tambah Menu</a>
        </div>
        <div class="spacer"></div>
        <div class="dt-responsive table-responsive">
            <table id="dtMenus" class="table table-striped table-bordered nowrap mytable" load-url="<?= Url::toRoute(['menus/draw-table']); ?>">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Path</th>
                        <th>Icon</th>
                        <th>Created at</th>
                        <th>Updated at</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Name</th>
                        <th>Path</th>
                        <th>Icon</th>
                        <th>Created at</th>
                        <th>Updated at</th>
                        <th>Action</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>

<?= $this->context->renderPartial('@app/modules/bo/views/manajemen/menus/_footer'); ?>