modules/juri/controllers/DefaultController.php
<?php

namespace app\modules\juri\controllers;

use Yii;
use app\controllers\BaseController as Controller;
use yii\filters\AccessControl;
use thamtech\uuid\helpers\UuidHelper;
use app\modules\eo\models\Event;
use app\modules\eo\models\EventPenilaian;
use app\modules\eo\models\Penilaian;
use app\modules\eo\models\Gantungan;
use app\modules\eo\models\TypePenilaian;
use app\modules\eo\models\TypeGantungan;
use app\modules\eo\models\JuriAssignment;

/**
 * Default controller for the `eo` module
 */
class DefaultController extends Controller
{
    public $layout = '@app/views/layouts/app.php';

    public $header;
    public $headerText;
    public $menu = '@app/modules/eo/views/default/menu/_mainmenu';

    public $backLink = 'default/event';

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'user' => 'userjuri',
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
    * List Section
    * ::Start
    */
    public function actionIndex()
    {
        $this->header = '@app/modules/juri/views/default/menu/_backheader';
        $this->headerText = "Penilaian";
        $this->menu = '@app/modules/juri/views/default/menu/_mainmenu';
        $this->backLink = 'default/index';

        $juri_id = \Yii::$app->userjuri->identity->getId() ?? null;
        $eventIds = JuriAssignment::find()
                            ->select('event_id')
                            ->distinct()
                            ->where(['juri_id' => $juri_id])
                            ->all();

        $in = [];
        foreach ($eventIds as $key => $eventId) {
            $in[] = $eventId->event_id;
        }

          
        $model['events'] = Event::find()
                                ->where(['in','id', $in])
                                ->all();
        
        return $this->render('@app/modules/juri/views/penilaian/lists', $model);
    }

    public function actionListsGantungan(){
        $this->header = '@app/modules/juri/views/default/menu/_backheader';
        $this->headerText = "Penilaian";
        $this->menu = '@app/modules/juri/views/default/menu/_mainmenu';

        $this->backLink = 'default/index';
        
        $event_id = \Yii::$app->request->get()['id'] ?? null;
        $juri_id = \Yii::$app->userjuri->identity->getId() ?? null;

        $event = Event::find()->where(['id' => $event_id])->one();
        
        $tipeGantungan = TypeGantungan::find()->where(['id' => $event->type_gantungan_id])->one();
        
        $col = $tipeGantungan->jumlah_col ?? 0;
        $row = $tipeGantungan->jumlah_row ?? 0;
        $type_gnt = $tipeGantungan->type_gnt ?? 0;
        
        $length = $row * $col;
        $chunk = $col;
        $loops = $this->snakeLoop($length, $chunk, $type_gnt);
        
        $gantungans = [];

        if(!empty($loops)){
            foreach ($loops as $k1 => $loop) {
                foreach ($loop as $k2  => $value) {
                    $_gantungan = Gantungan::find()
                                            ->where([
                                                    'event_id' => $event_id,
                                                    'no_gnt' => $value,
                                            ]);

                    $gantunganData = $_gantungan->one();

                    if(!empty($gantunganData)){
                        $_assignment = JuriAssignment::find()
                                                        ->where([
                                                            'event_id' => $event_id,
                                                            'gnt_id' => $gantunganData->id,
                                                            'juri_id' => $juri_id
                                                        ]);

                        $canAssignValue = ($_assignment->count() > 0);
                                                        
                        $gantungans[$k1][$k2]['id'] = $gantunganData->id;
                        $gantungans[$k1][$k2]['no_gnt'] = $gantunganData->no_gnt;
                        $gantungans[$k1][$k2]['event_id'] = $gantunganData->event_id;

                        $totalPoint = Penilaian::find()
                                    ->where([
                                        'gantungan_id' => $gantunganData->id,
                                        'juri_id' => $juri_id
                                    ])
                                    ->sum('nilai');

                        $gantungans[$k1][$k2]['totalPoint'] = $totalPoint ?? 0;
                        $gantungans[$k1][$k2]['canassign'] = $canAssignValue;
                    }
                }
            }
        }
        
        $model['gantungans'] = $gantungans;
        $model['column'] = $col;
        $model['tipePenilaian'] = EventPenilaian::find()
                                            ->where(['event_id' => $event_id])
                                            ->all();
        
        return $this->render('@app/modules/juri/views/penilaian/index', $model);
    }

    public function actionNilai(){
        $request = Yii::$app->request->post();
        $juri_id = \Yii::$app->userjuri->identity->getId() ?? null;
        $event_id = $request['event'] ?? null;

        Yii::$app->timeZone = 'Asia/Jakarta';

        $transaction = Yii::$app->db->beginTransaction();
        $nilai = TypePenilaian::findOne(['id' => $request['tipePenilaian']]);

        $callback = [];

        try {
            $penilaian = new Penilaian();
            $id = UuidHelper::uuid();
            $penilaian->id = $id;
            $penilaian->gantungan_id = $request['gantungan'] ?? null;
            $penilaian->type_nilai = $request['tipePenilaian'] ?? null;
            $penilaian->nilai = $nilai->nilai ?? null;
            $penilaian->juri_id = $juri_id ?? null;
            $penilaian->event_id = $event_id;
            $penilaian->timestmp = strtotime(date('Y-m-d H:i:s'));
            $penilaian->created_ad = date('Y-m-d H:i:s');

            if(!$penilaian->save()){
                throw Exception('Unable to save record.');
            }
            $transaction->commit();

            $callback['gantungan_id'] = $request['gantungan'];
            $callback['totalpoint'] = Penilaian::find()
                                        ->where([
                                            'gantungan_id' => $request['gantungan'],
                                            'juri_id' => $juri_id
                                        ])
                                        ->sum('nilai');
        } catch (\Throwable $th) {
            $transaction->rollback();
            return $this->asJsonError([$th->getMessage()],'[Error] Save data...');
        }
        return $this->asJsonSuccess($callback,'[Success] Save data...');
    }
     /**
      * List Section
      * ::End
      */

    private function snakeLoop($snakeLength, $chunk, $type = 'ASC'){
        function createArrayLoop($number){
            $temp = [];
            for ($i=1; $i <= $number ; $i++) { 
                $temp[$i] = $i;
            }

            return $temp;
        }

        $array = createArrayLoop($snakeLength);
        $newArrays = array_chunk($array, $chunk);
        
        if($type == 'DESC'){
            foreach ($newArrays as $key => $newArray) {
                $newArrays[$key] = array_reverse($newArray, true);
            }
        } else if($type === 'ASCSLINE'){
            foreach ($newArrays as $key => $newArray) {
                if(($key + 1) % 2 == 0){
                    $newArrays[$key] = array_reverse($newArray, true);
                }
            }
        } else if($type === 'DESCSLINE'){
            foreach ($newArrays as $key => $newArray) {
                $newArrays[$key] = array_reverse($newArray, true);
            }
            
            foreach ($newArrays as $key => $newArray) {
                if(($key + 1) % 2 == 0){
                    $newArrays[$key] = array_reverse($newArray, true);
                }
            }
        }

        return $newArrays;
    }

    public function actionSummaryPenilaian(){
        $this->layout = '@app/views/layouts/top.php';
        $this->header = '@app/modules/juri/views/default/menu/_backheader';
        $this->headerText = "Perolehan Nilai";
        $this->backLink = 'default/index';

        $event_id = Yii::$app->request->get()['id'] ?? null;
        $query = 'SELECT
                        g.id,
                        g.no_gnt,
                        IFNULL(g_score.total_nilai, 0) as total_nilai,
                        g.event_id
                    FROM
                        gantungan g
                    LEFT JOIN (
                        SELECT
                            gantungan_id,
                            SUM(nilai) as total_nilai,
                            event_id
                        FROM
                            penilaian
                        GROUP BY
                            gantungan_id,
                            event_id) as g_score ON
                        g_score.gantungan_id = g.id
                    WHERE g.event_id=:event_id
                    ORDER BY
                        g_score.total_nilai DESC';
        $lists= Yii::$app->db
                        ->createCommand($query)
                        ->bindValue('event_id',$event_id)
                        ->queryAll();
          
        $data = [];
        foreach ($lists as $list) {
            $data[$list['id']]['id'] = $list['id'];
            $data[$list['id']]['no_gnt'] = $list['no_gnt'];
            $data[$list['id']]['total_nilai'] = $list['total_nilai'];
            $data[$list['id']]['event_id'] = $list['event_id'];   

modules/juri/views/penilaian/index.php
<?php 
    use yii\helpers\Url; 
?>
<div class="container-fluid">
    <div class=AppGantungan>
        <div class="spacer"></div>
        <h5>Daftar Gantungan</h5>
        <div id="gantungan" class="gantungan" column="<?= $column; ?>">
            <?php 
                foreach ($gantungans as $key => $gantungan) {
                    echo '<div class="owl-carousel">';
                    foreach ($gantungan as $key => $record) {
                        if($record['canassign']){
            ?>
                    <div class="gantunganCol <?= ($record['canassign']) ? 'assignValue' : ''; ?>" gntId="<?= $record['id']; ?>" evId="<?= $record['event_id']; ?>">
                        <p><?= $record['no_gnt']; ?></p>
                        <div class="totalpoint">
                            <span>total point</span>
                            <span id="point-<?= $record['id']; ?>" class="point"><?= $record['totalPoint']; ?></span>
                        </div>
                    </div>
            <?php
                        }
                    }
                    echo '</div>';
                }
            ?>
        </div>
        <div class="modalGantungan">
            <div class="modalGantunganWrapper">
                <div class="gantunganTarget">
                    <?php 
                        if($tipePenilaian){
                            foreach ($tipePenilaian as $key => $value) {
                    ?>
                            <div class="btn" onclick="sendPenilaian(this, '<?= Url::toRoute(['default/nilai']); ?>')">
                                <input type="hidden" name="tpid" value="<?= $value->type_penilaian_id; ?>">
                                <?= $value->penilaian->nama_type??'-'; ?>
                            </div>
                    <?php
                            }
                        }else{
                            echo "<p>Jenis penilaian belum diatur</p>";
                        }
                    ?>
                </div>
                <div class="modalGantunganClose" onclick="closePreview()"><i class="uil uil-times"></i></div>
            </div>
        </div>
    </div>
</div>

modules/juri/views/penilaian/lists.php
<?php 
    use yii\helpers\Url;
    use app\modules\eo\models\JuriAssignment;
    use app\modules\eo\models\EventPenilaian;
    
    $this->title = 'GacorApp';
?>

<div class="AppEvent">
    <?php if (Yii::$app->session->hasFlash('success')): ?>
        <div class="alert alert-success alert-dismissable">
            <h4 style="font-size:11px"><i class="uil uil-check"></i>Success!</h4>
            <?= Yii::$app->session->getFlash('success') ?>
        </div>
    <?php endif; ?>

    <?php if (Yii::$app->session->hasFlash('error')): ?>
        <div class="alert alert-danger alert-dismissable">
            <h4 style="font-size:11px"><i class="uil uil-check"></i>Error!</h4>
            <?= Yii::$app->session->getFlash('error') ?>
        </div>
    <?php endif; ?>

    <?php 
        if(!empty($events)){
            foreach ($events as $key => $event) {
    ?>
            <div class="AppCard">
                <div class="body">
                    <div class="row">
                        <div class="col-xs-12">
                            <h5><?= $event->nama_event ?? ''; ?></h5>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-6">
                            <h4>
                                Tangal Event<br/>

                                <?php 
                                    $tgl_event = isset($event->tgl_event) ? date('d M Y',strtotime($event->tgl_event)) : '';
                                ?>
                                <span><?= $tgl_event; ?></span>
                            </h4>
                        </div>
                        <div class="col-xs-6">
                            <h4>Waktu<br/><span><?= $event->waktu ?? ''; ?></span></h4>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-6">
                            <h4>
                                Jenis Burung<br/>
                                <span>
                                    <?= $event->jenisBurung->name ?? ''; ?>
                                </span>
                            </h4>
                        </div>
                        <div class="col-xs-6">
                            <h4>
                                Kuota Peserta<br/>
                                <span>
                                    <?php 
                                        $jml_row = $event->tipeGantungan->jumlah_row ?? 0;
                                        $jml_col = $event->tipeGantungan->jumlah_col ?? 0;
                                        $kuota = intVal($jml_row) * intVal($jml_col); 
                                    ?>
                                    <?= $kuota ?? ''; ?>
                                </span>
                            </h4>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-4">
                            <h4>
                                Penilaian Khusus<br/>
                                <span>
                                    <?= ($event->is_khusus === 1) ? 'Ya' : 'Tidak'; ?>
                                </span>
                            </h4>
                        </div>
                    </div>
                </div>
                <div class="footer">
                <?php 
                    $actionJuri = ['add-juri/general','id' => $event->id];
                    if($event->is_khusus === 1)
                        $actionJuri = ['add-juri/spesific','id' => $event->id];
                ?>
                    <a href="<?= Url::toRoute(['penilaian-manual/lists-gantungan', 'id' => $event->id]); ?>" class="btn btn-success">
                        <i class="uil uil-edit"></i> Manual Input
                    </a>
                    <a href="<?= Url::toRoute(['default/lists-gantungan', 'id' => $event->id]); ?>" class="btn btn-primary">
                        <i class="uil uil-edit"></i> Manual Touch
                    </a>
                    <a href="<?= Url::toRoute(['default/summary-penilaian', 'id' => $event->id]); ?>" class="btn btn-warning">
                        <i class="uil uil-edit"></i> Perolehan Nilai
                    </a>
                </div>
            </div>
    <?php
            }
        }else{
    ?>
           <div class="AppCard">
                No Data
            </div>
    <?php 
        }
    ?>
</div>

<script>
</script>