modules/eo/models/Settings.php
<?php

namespace app\modules\eo\models;

class Settings extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'settings';
    }

    public function getUser(){
        return $this->hasOne(UserEo::className(), ['id' => ['user_id']]);
    }
}

modules/eo/controllers/EoAuthController.php
<?php

namespace app\modules\eo\controllers;

use Yii;
use app\controllers\BaseController as Controller;
use yii\web\Response;
use yii\helpers\Url;
use app\helpers\MyLibs;
use yii\widgets\ActiveForm;
use app\modules\eo\models\Event;
use app\modules\eo\models\EventPenilaian;
use app\modules\eo\models\TypePenilaian;
use app\modules\eo\models\PemilikTempat;
use app\modules\eo\models\UserEo;
use app\modules\eo\models\UserEoOtp;
use app\modules\eo\models\UserEoLogin as Login;
use app\modules\eo\models\form\EventForm;
use app\modules\eo\models\form\EventAddPenilaianForm;
use yii\filters\AccessControl;

/**
 * Eo Auth controller for the `eo` module
 */
class EoAuthController extends Controller
{
    public $layout = '@app/views/layouts/app.php';

    public $header;
    public $headerText;
    public $menu = '@app/modules/eo/views/default/menu/_mainmenu';

    public $backLink = 'default/event';

     /**
     * Gate Display Section
     * ::Start
     */

    //  Register Page
    public function actionRegister()
    {
        $this->checkGuest();
        
        $this->menu = '//default/_registermenu';
        $this->header = '//default/_registerheader';
        $this->headerText = 'Daftar EO';

        return $this->render('@app/modules/eo/views/auth/register');
    }
    
    public function actionDoRegister(){
        $this->checkGuest();

        $request = Yii::$app->request->post();
        $created_date = date('Y-m-d H:i:s');
        
        $transaction = Yii::$app->db->beginTransaction();

        try {
            $hash = Yii::$app->getSecurity();


            $model = new UserEo();
            $model->nama_lengkap = $request['nama_lengkap'];
            $model->username = $request['username'];
            $model->email = $request['username'];
            $model->password = $hash->generatePasswordHash($request['password']);
            $model->nohp = $request['notelp'];
            $model->created_ad = $created_date;

            if(!$model->save()){
                throw Exception('Unable to save record.');
            }

            Yii::$app->timeZone = 'Asia/Jakarta';
            
            $deleteBefore = UserEoOtp::deleteAll([ 'user_id'=>$model->id]);

            $otp = new UserEoOtp();
            $otp->id = $model->id;
            $otp->otp_code = MyLibs::digitRandom(6);
            $otp->otp_lifetime = date( "Y-m-d H:i:s", strtotime(date("Y-m-d H:i:s")." +5 minutes"));
            $otp->user_id = $model->id;
            
            if(!$otp->save()){
                throw Exception('Unable to save record.');
            }

            $html = Yii::$app->mailer
                               ->render(
                                    '@app/mail/otp', 
                                    ['otp_code' => $otp->otp_code], 
                                    '@app/mail/layouts/html'
                                );

            $mailData['fromName'] = 'Gacor Application';
            $mailData['senderName'] = 'no-reply@gacorapp.com';
            $mailData['to'] = $request['username'];
            $mailData['subject'] = 'Kode OTP Gacor Application';
            $mailData['konten'] = $html;

            MyLibs::SendMail($mailData);

            $callback['callback'] = Url::home(true).'eo/register-otp?otpid='.$otp->id;
            $transaction->commit();
        } catch (\Throwable $th) {
            $transaction->rollback();
            return $this->asJsonError([$th->getMessage()],'[Error] Save data...');
        }

        return $this->asJsonSuccess($callback,'[Success] Save data...');
    }

    public function actionOtp(){
        $this->checkGuest();

        $this->layout = '@app/views/layouts/top.php';
        $this->header = '//default/_registerheader';
        $this->headerText = 'Konfirmasi Kode OTP';

        $otpid = Yii::$app->request->get()['otpid'];

        $otp = UserEoOtp::findOne($otpid);

        if(empty($otp)){
            return $this->redirect(['eo-auth/not-found']);
        }

        $model['otpid'] = $otpid;

        return $this->render('@app/modules/eo/views/auth/otp', $model);
    }

    public function actionOtpConfirmed(){
        $this->checkGuest();

        $request = Yii::$app->request->post();

        $transaction = Yii::$app->db->beginTransaction();
        try {
            $userOtp = UserEoOtp::findOne(['id' => $request['otpid']]);

            if($userOtp->otp_code === $request['otpcode']){
                $user = UserEo::findOne(['id' => $userOtp->user_id]);
                $user->is_active = 1;
                $user->save();

                $message = ['callback' => Url::home(true).'eo/register-success' ];
            }else{
                return $this->asJsonError(['callback' => null],'Kode konfirmasi salah, silahkan ulangi');
            }

            $transaction->commit();
        } catch (\Exception $e) {
            $transaction->rollback();
            return $this->asJsonError([$th->getMessage()],'[Error] Save data...');
        }

        return $this->asJsonSuccess($message,'[Success] Save data...');
        
    }
    /**
     * Gate Register Section
     * ::End
     */
     
    /**
     * Login Display Section
     * ::Start
     */

    //  Login Page
    public function actionLogin()
    {
        $this->checkGuest();

        $this->layout = '@app/views/layouts/plain.php';
        
        return $this->render('@app/modules/eo/views/auth/login');
    }

    public function actionDoSignin(){
        $this->checkGuest();
        
        $model = new Login();
        $model->setAttributes(Yii::$app->request->post());

        $authenticate = $model->authenticate();

        if(!$authenticate['status']){
            return $this->asJsonError(['callback' => null], $authenticate['message']);
        }
       
        return $this->asJsonSuccess(['callback' => Url::home(true).'eo'],'[Success] Save data...');
    }
    /**
     * Login Display Section
     * ::End
     */

    public function actionLogout(){
        $this->checkGuest();

        \Yii::$app->usereo->logout(true);

        $this->redirect(['eo-auth/login']);
    }

    public function actionNotFound()
    {
        $this->layout = '@app/views/layouts/top.php';
        $this->header = '//default/_registerheader';
        $this->headerText = 'Halaman Tidak Ditemukan';

        return $this->render('notfound');
    }

    public function actionRegisterSuccess()
    {
        $this->layout = '@app/views/layouts/top.php';
        $this->header = '//default/_registerheader';
        $this->headerText = 'Pendaftaran Berhasil';

        return $this->render('@app/modules/eo/views/auth/registersucces');
    }

    public function checkGuest(){
        if (!\Yii::$app->usereo->isGuest) return $this->redirect(['default/index']);
    }
}

modules/eo/controllers/SettingsController.php
<?php

namespace app\modules\eo\controllers;

use Yii;
use app\controllers\BaseController as Controller;
use yii\web\Response;
use yii\helpers\Url;
use thamtech\uuid\helpers\UuidHelper;
use yii\filters\AccessControl;
use app\modules\eo\models\form\SettingsForm;
use app\modules\eo\models\PemilikTempat;

/**
 * Default controller for the `eo` module
 */
class SettingsController extends Controller
{
    public $layout = '@app/views/layouts/app.php';

    public $header;
    public $headerText;
    public $menu = '@app/modules/eo/views/default/menu/_mainmenu';

    public $backLink = 'default/event';

    public function actionIndex(){
        return $this->render('@app/modules/eo/views/settings/index');
    }

    public function actionHariTempat(){
        $this->header = '@app/modules/eo/views/default/menu/_backheader';
        $this->headerText = "Settings - Hari & Tempat Pelaksanaan";
        $this->menu = '@app/modules/eo/views/settings/haritempat/_savemenu';
        
        $this->backLink = 'settings/index';
        
        $userid = Yii::$app->usereo->identity->getId() ?? ''; 

        $pemilik = PemilikTempat::find()->where(['user_id' => $userid]);
        $owner = $pemilik->one();

        $model['owner'] = $owner;

        $jadwal = [];
        if(!empty($owner))
            $jadwal = explode(",",$owner->jadwal_pelaksanaan);
        
        $model['minggu'] = in_array("0", $jadwal) ? 'checked' : '';
        $model['senin'] = in_array("1", $jadwal) ? 'checked' : '';
        $model['selasa'] = in_array("2", $jadwal) ? 'checked' : '';
        $model['rabu'] = in_array("3", $jadwal) ? 'checked' : '';
        $model['kamis'] = in_array("4", $jadwal) ? 'checked' : '';
        $model['jumat'] = in_array("5", $jadwal) ? 'checked' : '';
        $model['sabtu'] = in_array("6", $jadwal) ? 'checked' : '';

        if($pemilik->count() < 1){
            $new = new PemilikTempat();
            $new->created_ad = date('Y-m-d H:i:s');
            $new->user_id = $userid;
            $new->save();
        }

        return $this->render('@app/modules/eo/views/settings/haritempat/index',$model);
    }

    public function actionHariTempatUpdate(){
        $request = Yii::$app->request->post();
        $userid = Yii::$app->usereo->identity->getId() ?? ''; 

        $jadwal_pelaksanaan = !empty($request['jadwal_pelaksanaan']) ? implode(",",$request['jadwal_pelaksanaan']) : null;
       
        $transaction = Yii::$app->db->beginTransaction();
        Yii::$app->timeZone = 'Asia/Jakarta';

        try {
            $pemilik = PemilikTempat::findOne(['user_id' => $userid]);
            $pemilik->nama_pemilik = $request['nama_pemilik'];
            $pemilik->notlp = $request['notlp'];
            $pemilik->alamat = $request['alamat'];
            $pemilik->jadwal_pelaksanaan = $jadwal_pelaksanaan;
            $pemilik->user_id = $userid;
            $pemilik->updated_ad = date('Y-m-d H:i:s');

            if(!$pemilik->save()){
                throw Exception('Unable to save record.');
            }

            $callback['callback'] = Url::home(true).'eo/settings';
            $transaction->commit();
        } catch (\Throwable $th) {
            $transaction->rollback();
            return $this->asJsonError([$th->getMessage()],'[Error] Save data...');
        }

        return $this->asJsonSuccess($callback,'[Success] Save data...');
    }
}

modules/eo/controllers/TipeGantunganController.php
<?php

namespace app\modules\eo\controllers;

use Yii;
use yii\web\Controller;
use yii\web\Response;
use yii\widgets\ActiveForm;
use app\modules\eo\models\TypeGantungan;
use app\modules\eo\models\form\TipeGantunganForm;

/**
 * Default controller for the `eo` module
 */
class TipeGantunganController extends Controller
{
    public $layout = '@app/views/layouts/app.php';

    public $header;
    public $headerText;
    public $menu = '@app/modules/eo/views/default/menu/_mainmenu';

    public $backLink = 'settings/tipe-gantungan';

    public $permitted_chars = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
    
    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }
   
    /**
     * List Section
     * ::Start
     */
    public function actionGantungan()
    {
        $this->header = '@app/modules/eo/views/default/menu/_backheader';
        $this->headerText = "Settings: List Tipe Gantungan";
        $this->menu = '@app/modules/eo/views/settings/tipe_gantungan/_mainmenu';

        $this->backLink = 'settings/index';

        $model['typeGantungans'] = TypeGantungan::find()->orderBy(['id' => SORT_DESC])->all();

        return $this->render('@app/modules/eo/views/settings/tipe_gantungan/index', $model);
    }
    /**
     * List Section
     * ::End
     */

    /**
     * Create Section
     * ::Start
     */
    public function actionCreate()
    {
        $this->header = '@app/modules/eo/views/default/menu/_backheader';
        $this->headerText = "Settings - Create Tipe Gantungan";
        $this->menu = '@app/modules/eo/views/settings/tipe_gantungan/_savemenu';

        $model['tipeGantunganModel'] = new TipeGantunganForm();

        return $this->render('@app/modules/eo/views/settings/tipe_gantungan/create', $model);
    }

    public function actionSave(){
        $request = Yii::$app->request->post()['TipeGantunganForm'];

        $transaction = Yii::$app->db->beginTransaction();

        try {
            $model = new TypeGantungan();
            $model->name = $request['name'];
            $model->jumlah_row = $request['jumlah_row'];
            $model->jumlah_col = $request['jumlah_col'];
            $model->type_gnt = $request['type_gnt'];
            $model->created_ad = date('Y-m-d H:i:s');
            $model->save();
            
            Yii::$app->getSession()->setFlash('success', 'Your tipe gantungan was created successfully!');

            $transaction->commit();
        } catch (\Throwable $th) {
            Yii::$app->getSession()->setFlash('error', $th->getMessage().'Error while submitting your tipe gantungan.');

            $transaction->rollback();
        }

        return $this->redirect(['tipe-gantungan/gantungan']);
    }
    /**
     * Create Section
     * ::End
     */

    /**
     * Edit Section
     * ::Start
     */
    public function actionEdit()
    {
        $this->header = '@app/modules/eo/views/default/menu/_backheader';
        $this->headerText = "Event - Edit Tipe Gantungan";
        $this->menu = '@app/modules/eo/views/settings/tipe_gantungan/_savemenu';

        $id = Yii::$app->request->get()['id'];
        $tipeGantungan = TypeGantungan::findOne($id);

        $model = new TipeGantunganForm();
        $model->id = $tipeGantungan->id;
        $model->name = $tipeGantungan->name;
        $model->jumlah_row =  $tipeGantungan->jumlah_row;
        $model->jumlah_col = $tipeGantungan->jumlah_col;
        $model->type_gnt = $tipeGantungan->type_gnt;
            
        $data['tipeGantunganModel'] =$model;

        return $this->render('@app/modules/eo/views/settings/tipe_gantungan/edit', $data);
    }

    public function actionUpdate(){
        $request = Yii::$app->request->post()['TipeGantunganForm'];
        $transaction = Yii::$app->db->beginTransaction();
        $userid = Yii::$app->usereo->identity->getId() ?? ''; 

        try {
            $model = TypeGantungan::findOne($request['id']);
            $model->name = $request['name'];
            $model->jumlah_row =  $request['jumlah_row'];
            $model->jumlah_col = $request['jumlah_col'];
            $model->type_gnt = $request['type_gnt'];
            $model->updated_ad = date('Y-m-d H:i:s');
            $model->save();
            
            Yii::$app->getSession()->setFlash('success', 'Your tipe gantungan was edited successfully!');

            $transaction->commit();
        } catch (\Throwable $th) {
            Yii::$app->getSession()->setFlash('error', 'Error while editing your tipe gantungan.'.$th->getMessage());

            $transaction->rollback();
        }

        return $this->redirect(['tipe-gantungan/gantungan']);
    }
    /**
     * Edit Section
     * ::End
     */

    /**
    * Delete Section
    * ::Start
    */
    public function actionDelete(){
        $id = Yii::$app->request->get()['id'];
        
        $transaction = Yii::$app->db->beginTransaction();
        try {
            $model = TypeGantungan::findOne($id)->delete();

            $transaction->commit();
            
            Yii::$app->getSession()->setFlash('success', 'Your tipe gantungan was deleted successfully!');
        } catch (\Throwable $th) {
            //throw $th;
            $transaction->rollback();
            Yii::$app->getSession()->setFlash('error', 'Error while deleting your tipe gantungan.');
        }

        return $this->redirect(['juri/juri']);
    }
    /**
     * Delete Section
     * ::End
     */
 
    function generate_string($input, $strength = 16) {
        $input_length = strlen($input);
        $random_string = '';
        for($i = 0; $i < $strength; $i++) {
            $random_character = $input[mt_rand(0, $input_length - 1)];
            $random_string .= $random_character;
        }
    
        return $random_string;
    }
}

modules/eo/views/settings/tipe_gantungan/_form.php
<div class="row">
    <div class="col-xs-12">
        <?= $form->field($tipeGantunganModel, 'name')->textInput()->label('Judul') ?>
    </div>
</div>
<div class="row">
    <div class="col-xs-6">
        <?= $form->field($tipeGantunganModel, 'jumlah_row')->textInput(['id' => 'jml_col'])->label('Jumlah Baris') ?>
    </div>
    <div class="col-xs-6">
        <?= $form->field($tipeGantunganModel, 'jumlah_col')->textInput(['id' => 'jml_row'])->label('Jumlah Kolom') ?>
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <?php echo $form->field($tipeGantunganModel, 'type_gnt')->dropdownList([
                            'ASC' => 'ASC', 
                            'DESC' => 'DESC',
                            'ASCSLINE' => 'ASC - SLINE',
                            'DESCSLINE' => 'DESC - SLINE',
                        ],
                        ['prompt'=>'Pilih Tipe Gantungan'],
                        ['id' => 'type_gnt']
                    )->label('Tipe Gantungan'); 
        ?>
    </div>
</div>

modules/eo/views/settings/tipe_gantungan/_mainmenu.php
<?php use yii\helpers\Url; ?>
<div class="AppMainMenu">
    <a href="<?= Url::toRoute(['default/index']); ?>" class="AppMainMenu__button AppMainMenu--active">
        <i class="AppMainMenu__icon uil uil-home-alt"></i>
        <span>Beranda</span>
    </a>
    <a href="<?= Url::toRoute(['tipe-gantungan/create']); ?>" class="AppMainMenu__button">
        <i class="AppMainMenu__icon uil uil-plus"></i>
        <span>Create</span>
    </a>
    <a href="<?= Url::toRoute(['eo-auth/logout']); ?>" class="AppMainMenu__button">
        <i class="AppMainMenu__icon uil uil-sign-out-alt"></i>
        <span>Keluar</span>
    </a>
</div>

modules/eo/views/settings/tipe_gantungan/_savemenu.php
<?php use yii\helpers\Url; ?>
<div class="AppMainMenu">
    <button class="btn AppMainMenu__submitButton AppForm--btnSave" onclick="submit('tipeGantunganForm')">
        <i class="uil uil-save"></i> <br/>Save
    </button>
    <button class="btn AppMainMenu__submitButton AppForm--btnPreview" onclick="preview('tipegantunganform')">
        <i class="uil uil-eye"></i> <br/>Preview
    </button>
</div>

modules/eo/views/settings/tipe_gantungan/create.php
<?php 
    use yii\helpers\Html;
    use yii\widgets\ActiveForm;
    use kartik\date\DatePicker;

    $this->title = 'GacorApp';
?>
<div class="container-fluid">
    <div class="AppForm">
        <?php 
            $form = ActiveForm::begin([
                'action' => ['tipe-gantungan/save'],
                'method' => 'POST',
                'id' => 'tipeGantunganForm',
                // 'enableAjaxValidation' => true,
                'enableClientValidation'=>true,
                // 'validationUrl' => ['default/ajax-validation'],
                'options' => ['class' => 'form-horizontal'],
            ]);
        ?>

        <?= $this->render('@app/modules/eo/views/settings/tipe_gantungan/_form', [
                            'form' => $form, 
                            'tipeGantunganModel' => $tipeGantunganModel,
                        ]); ?>

        <?php ActiveForm::end() ?>
        
        <div class="preview">
            <div class="previewWrapper">
                <div id="previewTarget"></div>
                <div class="closeBtn" onclick="closePreview()"><i class="uil uil-times"></i></div>
            </div>
        </div>
    </div>
</div>

modules/eo/views/settings/tipe_gantungan/edit.php
<?php 
    use yii\helpers\Html;
    use yii\widgets\ActiveForm;
    use kartik\date\DatePicker;

    $this->title = 'GacorApp';
?>
<div class="container-fluid">
    <div class="AppForm">
        <?php 
            $form = ActiveForm::begin([
                'action' => ['tipe-gantungan/update'],
                'method' => 'POST',
                'id' => 'tipeGantunganForm',
                // 'enableAjaxValidation' => true,
                'enableClientValidation'=>true,
                // 'validationUrl' => ['default/ajax-validation'],
                'options' => ['class' => 'form-horizontal'],
            ]);
        ?>

        
        <?php 
            echo $form->field($tipeGantunganModel, 'id')
                    ->hiddenInput(['value'=> $tipeGantunganModel->id])->label(false);
        ?>

        <?= $this->render('@app/modules/eo/views/settings/tipe_gantungan/_form', [
                            'form' => $form, 
                            'tipeGantunganModel' => $tipeGantunganModel,
                        ]); ?>

        <?php ActiveForm::end() ?>
        
        <div class="preview">
            <div class="previewWrapper">
                <div id="previewTarget"></div>
                <div class="closeBtn" onclick="closePreview()"><i class="uil uil-times"></i></div>
            </div>
        </div>
    </div>
</div>

modules/eo/views/settings/tipe_gantungan/index.php
<?php 
    use yii\helpers\Url;
    
    $this->title = 'GacorApp';
?>

<div class="AppEvent">
    <?php if (Yii::$app->session->hasFlash('success')): ?>
        <div class="alert alert-success alert-dismissable">
            <h4 style="font-size:11px"><i class="uil uil-check"></i>Success!</h4>
            <?= Yii::$app->session->getFlash('success') ?>
        </div>
    <?php endif; ?>

    <?php if (Yii::$app->session->hasFlash('error')): ?>
        <div class="alert alert-danger alert-dismissable">
            <h4 style="font-size:11px"><i class="uil uil-check"></i>Error!</h4>
            <?= Yii::$app->session->getFlash('error') ?>
        </div>
    <?php endif; ?>

    <?php 
        if(!empty($typeGantungans)){
            foreach ($typeGantungans as $key => $gantungan) {
    ?>
            <div class="AppCard">
                <div class="body">
                    <div class="row">
                        <div class="col-xs-12">
                            <h5><?= $gantungan->name ?? ''; ?></h5>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-6">
                            <h4>
                                Jumlah Baris<br/>
                                <span><?= $gantungan->jumlah_row ?? ''; ?></span>
                            </h4>
                        </div>
                        <div class="col-xs-6">
                            <h4>
                                Jumlah Kolom<br/>
                                <span><?= $gantungan->jumlah_col ?? ''; ?></span>
                            </h4>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-6">
                            <h4>
                                Tipe gantungan<br/>
                                <span><?= $gantungan->type_gnt ?? ''; ?></span>
                            </h4>
                        </div>
                        <div class="col-xs-6">
                            <h4>
                                Kouta Peserta<br/>
                                <?php 
                                    $kuota = intval($gantungan->jumlah_col) * intval($gantungan->jumlah_row);
                                ?>
                                <span><?= $kuota ?? 0; ?></span>
                            </h4>
                        </div>
                    </div>
                </div>
                <div class="footer">
                    <a href="<?= Url::toRoute(['tipe-gantungan/edit', 'id' => $gantungan->id]); ?>" class="btn btn-primary"><i class="uil uil-edit"></i> Edit</a>
                    <a href="javascript:void(0)" class="btn btn-danger" onclick="deleteData('<?= Url::toRoute(['tipe-gantungan/delete','id' => $gantungan->id]); ?>')"><i class="uil uil-trash"></i> Delete</a>
                </div>
            </div>
    <?php
            }
        }else{
    ?>
            <div class="AppCard">
                No Data
            </div>
    <?php 
        }
    ?>
</div>

<script>
</script>